
services:
  hpc_base:
    env_file:
      - .env
    image: hpc_base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    build:
      context: ../
      dockerfile: ./parallel_env/Dockerfile.hpc_base
      args:
        - PRIMARY_UID=${UID}
        - PRIMARY_GID=${GID}
        - PRIMARY_USER=gen_user

    container_name: hpc_base
    entrypoint:
      [
        "/bin/bash",
        "/usr/local/entrypoints/entrypoint_simple_persistence.sh"
      ]
    volumes:
      - ${LOCAL_PROJECT_ROOT}:/home/gen_user/project
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "127.0.0.1:8888:8888"

    init: true
    stdin_open: true
    tty: true





